
// const char strings
const char s_0[] PROGMEM =  "AMBIVALENCE CAN RUIN YOUR LIFE";
const char s_1[] PROGMEM =  "AN ELITE IS INEVITABLE";
const char s_2[] PROGMEM =  "ANIMALISM IS PERFECTLY HEALTHY";
const char s_3[] PROGMEM =  "ANY SURPLUS IS IMMORAL";
const char s_4[] PROGMEM =  "AUTOMATION IS DEADLY";
const char s_5[] PROGMEM =  "CATEGORIZING FEAR IS CALMING";
const char s_6[] PROGMEM =  "DECENCY IS A RELATIVE THING";
const char s_7[] PROGMEM =  "DEPENDENCE CAN BE A MEAL TICKET";
const char s_8[] PROGMEM =  "EATING TOO MUCH IS CRIMINAL";
const char s_9[] PROGMEM =  "EVEN YOUR FAMILY CAN BETRAY YOU";
const char s_10[] PROGMEM = "EXPRESSING ANGER IS NECESSARY";
const char s_11[] PROGMEM = "FATHERS OFTEN USE TOO MUCH FORCE"; //
const char s_12[] PROGMEM = "HUMANISM IS OBSOLETE";
const char s_13[] PROGMEM = "HUMOR IS A RELEASE";
const char s_14[] PROGMEM = "ILLNESS IS A STATE OF MIND";
const char s_15[] PROGMEM = "INHERITANCE MUST BE ABOLISHED";
const char s_16[] PROGMEM = "ILLNESS IS A STATE OF MIND";
const char s_17[] PROGMEM = "IT IS HEROIC TO TRY TO STOP TIME"; //
const char s_18[] PROGMEM = "LACK OF CHARISMA CAN BE FATAL";
const char s_19[] PROGMEM = "LISTEN WHEN YOUR BODY TALKS";
const char s_20[] PROGMEM = "MEN ARE NOT MONOGAMOUS BY NATURE"; //
const char s_21[] PROGMEM = "MODERATION KILLS THE SPIRIT";
const char s_22[] PROGMEM = "MONEY CREATES TASTE";
const char s_23[] PROGMEM = "MORALS ARE FOR LITTLE PEOPLE";
const char s_24[] PROGMEM = "MURDER HAS ITS SEXUAL SIDE";
const char s_25[] PROGMEM = "NOISE CAN BE HOSTILE";
const char s_26[] PROGMEM = "PHYSICAL CULTURE IS SECOND BEST";
const char s_27[] PROGMEM = "PRIVATE PROPERTY CREATED CRIME";
const char s_28[] PROGMEM = "RECLUSES ALWAYS GET WEAK";
const char s_29[] PROGMEM = "RAISE BOYS & GIRLS THE SAME WAY";
const char s_30[] PROGMEM = "RELATIVITY IS NO BOON TO MANKIND"; //
const char s_31[] PROGMEM = "ROUTINE IS A LINK WITH THE PAST";
const char s_32[] PROGMEM = "SALVATION CAN'T BE BOUGHT & SOLD";
const char s_33[] PROGMEM = "SELF-AWARENESS CAN BE CRIPPLING";
const char s_34[] PROGMEM = "SEX DIFFERENCES ARE HERE TO STAY"; //
const char s_35[] PROGMEM = "SIN IS A MEANS OF SOCIAL CONTROL"; //
const char s_36[] PROGMEM = "SOLITUDE IS ENRICHING";
const char s_37[] PROGMEM = "STARVATION IS NATURE'S WAY";
const char s_38[] PROGMEM = "STASIS IS A DREAM STATE";
const char s_39[] PROGMEM = "STUPID PEOPLE SHOULDN'T BREED";
const char s_40[] PROGMEM = "TECHNOLOGY WILL MAKE OR BREAK US"; // 
const char s_41[] PROGMEM = "THE MUNDANE IS TO BE CHERISHED";
const char s_42[] PROGMEM = "TIMIDITY IS LAUGHABLE";
const char s_43[] PROGMEM = "TO VOLUNTEER IS REACTIONARY";
const char s_44[] PROGMEM = "TORTURE IS BARBARIC";
const char s_45[] PROGMEM = "TRUE FREEDOM IS FRIGHTFUL";
const char s_46[] PROGMEM = "WAR IS A PURIFICATION RITE";
const char s_47[] PROGMEM = "WORDS TEND TO BE INADEQUATE";
const char s_48[] PROGMEM = "WORRYING CAN HELP YOU PREPARE";
const char s_49[] PROGMEM = "YOU ARE GUILELESS IN YOUR DREAMS"; //
const char s_50[] PROGMEM = "YOU MUST HAVE ONE GRAND PASSION";

const char * const truisms[] PROGMEM = {
  s_0, s_1, s_2, s_3, s_4, s_5, s_6, s_7, s_8, s_9, s_10, s_11, s_12, s_13, s_14, s_15, s_16, s_17, s_18, s_19, s_20, s_21, s_22, s_23, s_24, s_25, s_26, s_27, s_28, s_29, s_30, s_31, s_32, s_33, s_34, s_35, s_36, s_37, s_38, s_39, s_40, s_41, s_42, s_43, s_44, s_45, s_46, s_47, s_48, s_49, s_50
};
